[build]
command = "npm run build"
publish = "_site"


[dev]
command = "npm run dev"
port = 8888
publish = "_site"


# Optional: redirect /blog to home or vice versa later
# [[redirects]]
# from = "/blog"
# to = "/"
# status = 200